const mongoose = require('mongoose');

const dailyTaskInstanceSchema = new mongoose.Schema(
  {
    employeeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: true,
      index: true,
    },
    taskTemplateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'TaskTemplate',
      default: null,
      index: true,
    },
    dateKey: {
      type: String,
      required: true,
      trim: true,
      index: true,
      validate: {
        validator: (value) => /^\d{4}-\d{2}-\d{2}$/.test(String(value || '').trim()),
        message: 'dateKey must be in YYYY-MM-DD format',
      },
    },
    date: {
      type: Date,
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 120,
    },
    description: {
      type: String,
      default: '',
      trim: true,
      maxlength: 500,
    },
    assignedRole: {
      type: String,
      enum: ['waiter', 'cook', 'captain', 'manager', 'employee', 'all'],
      default: 'all',
    },
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: 'medium',
    },
    status: {
      type: String,
      enum: ['pending', 'completed', 'cancelled'],
      default: 'pending',
      index: true,
    },
    completed: {
      type: Boolean,
      default: false,
      index: true,
    },
    completedAt: {
      type: Date,
      default: null,
    },
    completedByUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    autoGenerated: {
      type: Boolean,
      default: true,
    },
    source: {
      type: String,
      enum: ['template', 'manual'],
      default: 'template',
    },
    cartId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },
    franchiseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

dailyTaskInstanceSchema.index(
  {
    employeeId: 1,
    taskTemplateId: 1,
    dateKey: 1,
  },
  {
    unique: true,
    name: 'daily_task_employee_template_date_uniq',
    partialFilterExpression: {
      taskTemplateId: { $type: 'objectId' },
    },
  }
);

dailyTaskInstanceSchema.index(
  {
    employeeId: 1,
    dateKey: 1,
    status: 1,
    completed: 1,
  },
  {
    name: 'daily_task_employee_date_status_idx',
  }
);

module.exports = mongoose.model('DailyTaskInstance', dailyTaskInstanceSchema);
